import About from '../components/about/About'
import Banner from '../components/banner/Banner'
import Contact from '../components/contact/Contact'
import Footer from '../components/footer/Footer'
import Head from 'next/head'
import Hero from '../components/hero/Hero'
import Image from 'next/image'
import Nav from '../components/nav/Nav'
import Projects from '../components/projects/Projects'
import Reputation from '../components/reputation/Reputation'
import Services from '../components/services/Services'
import ServicesImgText from '../components/services/ServicesImgText'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <Nav />
      </header>

      <main>
        <Hero />
        <Reputation />
        <About />
        <button className='btn btn-primary'>Button</button>
        <button className='btn btn-white'>Button</button>
        <button className='btn btn-black'>Button</button>
        <button className='btn btn-light'>Button</button>
        <button className='btn btn-variant'>Button</button>
        <Services />
        <ServicesImgText />
        <Banner />
        <Projects />
        <Contact />
      </main>

      <footer>
        <Footer />
      </footer>
    </div>
  )
}
