import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <p>Nav</p>
      </header>

      <main>
        <p>Hero</p>
        <p>Reputation</p>
        <p>About</p>
        <p>Services</p>
        <p>Services img/text</p>
        <p>Banner</p>
        <p>Projects</p>
        <p>Contact</p>
      </main>

      <footer>
        <p>Footer</p>
      </footer>
    </div>
  )
}
